name: Puppeteer

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Firefox
        run: sudo apt-get update && sudo apt-get install -y firefox

      - run: pnpm install
      - run: pnpm test -- --run