name: Puppeteer

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - name: Fix rollup bug
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Firefox
        run: sudo apt-get update && sudo apt-get install -y firefox

      - name: Run
        run: npm run test
        env:
          PUPPETEER_PRODUCT: firefox
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/firefox
